config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/folder')
  get "/sign_up", to: 'session#show'
  post "/sign_up", to: 'session#signup', as: 'signup'
  get 'logout', to: 'session#logout', as: 'logout'

  resources :ext_images do
  end
  resources :folders do
    get 'upload', on: :member
  end
  get '/folder', to: 'folders#show', as: 'folders_root'
  post '/ext_image/:id/destroy', to: 'ext_images#destroy', as: 'ext_image_delete'

  post '/uploads/common_images', to: 'common_uploads#common_image', as: 'common_images_upload'

  namespace :scanlet do
    resources :projects
    resources :groups do
      member do
        get 'translations'
      end
    end
    resources :translations, only: [:show, :new, :create]
    get '/groups/:group/add_scan', to: 'translations#new', as: 'add_scan_to_group'
  end
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :images, class_name: ExtImage.name
  has_many :children, class_name: Folder.name, dependent: :restrict_with_error, foreign_key: 'parent_id'
  belongs_to :parent, class_name: Folder.name, required: false
  validates :name, presence: true, uniqueness: true, format: {with: /\A[\w]+[\-\w\/]*[\w]?\z/i}
  before_validation :fix_name
  before_save :full_path, if: :will_save_change_to_name?
  before_update :full_path, if: :will_save_change_to_name?

  after_save :update_child_paths, if: :saved_change_to_path?
  after_update :update_child_paths, if: :saved_change_to_path?

  def self.trash
    Folder.find_by_path('/trash')
  end

  protected
  def fix_name
    folder = self.name

    folder = folder.strip
    folder.slice!(0) if folder[0] == '/'
    folder.chop! if folder[folder.length-1] == '/'

    self.name = folder
  end

  def full_path
    folder = self.name
    if self.parent.nil?
      self.path = '/' + folder
    else
      self.path = self.parent.path + "/" + folder
    end
  end

  def update_child_paths
    self.reload
    self.children.each do |child|
      child.full_path
      child.save
    end
  end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  include ImagesHelper

  before_action :check_session!

  def index
    @folders = Folder.all.order(:name)
    p @folders.size
    respond_to do |format|
      format.json {render json: {result: 0, data: @folders.to_a.map {|f| {id: f.id, path: f.path, parent: f.parent&.id}}}}
      format.html {render 'index'}
    end
  end

  def show
    query = {}
    query['id'] = params['id'] if params['id'].present?
    path = request.query_parameters['path']
    query['path'] = path unless path.blank?
    if query.empty?
      @folders = Folder.where(parent: nil).order(:name)
    else
      current = Folder.where(query).first
      if current.present?
        @current = current
        @folders = current.children.order(:name)
        @files = current.images.order(created_at: :desc)
      else
      end
    end
    @files = @files || []
    respond_to do |format|
      format.json {
        if @folders.nil?
          render status: 404, json: {}
        else
          render json: {
            result: 0,
            folders: @folders.map {|f| {id: f.id, name: f.name, parent: f.parent&.id}},
            files: @files.map {|f| {
              id: f.id,
              url: f.image.url
            }}
          }
        end
      }
      format.html {
        if @folders.nil?
          render status: 404
        else
          render 'show'
        end
      }
    end
  end

  def create
    p = folder_params
    parent_id = p['parent']
    parent = parent_id.present? ? Folder.find(parent_id) : nil
    f = Folder.create(name: p['name'], parent: parent)
    if f.valid?
      respond_to do |format|
        format.json {render json: {result: 0, id: f.id, path: f.path, parent: f.parent.try(:id)}}
        format.html {
          if request.xhr?
            @folders = Folder.where(parent: f.parent.try(:id)).order(:name)
            render :partial => 'folders_list'
          else
            redirect_to action: :show, id: f.id
          end
        }
      end
    end
  end

  def update
    f = Folder.find(params[:id])
    render status: 404, plain: "Not found" if f.nil?
    res = f.update(params.permit('name'))
    if res
      respond_to do |format|
        format.json {render json: {result: 0}}
      end
    else
      respond_to do |format|
        format.json {render status: 400, json: {result: -1, errors: f.errors.messages[:name]}}
      end
    end
  end

  def destroy
    id = params['id']
    f = Folder.find(id)
    render status: 404, json: {} and return if f.nil?
    if f.children.empty?
      res = f.destroy
      render status: 200, json: {} and return if res
      render status: 402, plain: f.errors.messages
    else
      render status: 402, plain: 'Forbidden: the folder is not empty'
    end
  end

  def upload
    f = Folder.find(params['id'])
    render status: 404, json: {} and return if f.nil?
    @folder = f
    render 'folders/upload'
  end


  private

  def folder_params
    params.require(:name)
    params.permit(:name, :parent)
  end
end

app/views/folders/_folders_list.html.erb
<ul class="list-group" name="folders-list">
  <% @folders.each do |f| %>
      <li class="list-group-item">
        <%= link_to f.name, folder_path(f) %>
      </li>
  <% end %>
</ul>

app/views/folders/index.html.erb
<div class="row folders">
  <div class="col-xs-12">
    <h1>Folders index</h1>
    <div class="item">
      <%= link_to "/", folders_root_path %>
    </div>
      <% for folder in @folders %>
        <div class="item">
          <%= link_to folder.path, folder_path(folder) %>
        </div>
      <% end %>
  </div>
</div>

app/views/folders/show.html.erb
<input type="hidden" name="scope-object" value="<%= @current.present? ? @current.id : '' %>">
<div class="row">
  <div class="col-xs-12">
    <h1><%= @current.present? ? @current.path : "/" %></h1>
    <div class="panel panel-default">
      <div class="panel-heading">Folders</div>
      <div class="panel-body">
        <div class="errors bg-danger"></div>
        <div class="row">
          <div class="col-xs-12 col-sm-7 col-md-5">
            <div class="input-group">
              <input type="text" class="form-control" name="folder-name">
              <span class="input-group-btn">
                <button class="btn btn-default" name="create-folder" type="button">Create</button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <%= render partial: 'folders_list' %>
    </div>
    <% if @current.present? %>
        <div class="panel panel-default">
          <div class="panel-heading">Files</div>
          <div class="panel-body">
            <%= link_to 'Upload images', upload_folder_path(@current), class: 'btn btn-success upload' %>
          </div>

          <ul class="list-group images-list">
            <% @files.each do |f| %>
                <li class="list-group-item">
                  <%= render partial: 'ext_images/ext_image', locals: {ext_image: f}  %>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>
  </div>
</div>

app/views/folders/upload.html.erb
<h1><%= @folder.path %></h1>
<div class="back-to-folder">
  <%= link_to folder_path(@folder) do %>
    <i class="glyphicon glyphicon-folder-open"></i><span> Back to <%= @folder.name %></span>
  <% end %>
</div>
<%= render partial: 'ext_images/upload_panel', locals: {folder_id: @folder.id}%>