config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/folder')
  get "/sign_up", to: 'session#show'
  post "/sign_up", to: 'session#signup', as: 'signup'
  get 'logout', to: 'session#logout', as: 'logout'

  resources :ext_images do
  end
  resources :folders do
    get 'upload', on: :member
  end
  get '/folder', to: 'folders#show', as: 'folders_root'
  post '/ext_image/:id/destroy', to: 'ext_images#destroy', as: 'ext_image_delete'

  post '/uploads/common_images', to: 'common_uploads#common_image', as: 'common_images_upload'

  namespace :scanlet do
    resources :projects
    resources :groups do
      member do
        get 'translations'
      end
    end
    resources :translations, only: [:show, :new, :create]
    get '/groups/:group/add_scan', to: 'translations#new', as: 'add_scan_to_group'
  end
end

app/models/ext_image.rb
class ExtImage < ApplicationRecord
  mount_uploader :image, ExtImageUploaderS3
  validates :image, presence: true
  belongs_to :folder, class_name: Folder.name, required: false

  def self.new_from_disk(path)
    image = ExtImage.new
    File.open path do |f|
      image.image = f
    end
    image
  end

  def self.upload_from_disk(path)
    image = ExtImage.new
    File.open path do |f|
      image.image = f
    end
    image.save!
    image
  end

  def preview
    return image.thumb if image.thumb.present?
    image
  end

  def to_trash
    trash = Folder.trash
    self.folder = trash
    save
  end

end

app/controllers/ext_images_controller.rb
class ExtImagesController < ApplicationController
  include ImagesHelper

  helper_method :original_url

  before_action :check_session!
  before_action :set_image, only: [:destroy, :show]


  def index
    @images = ExtImage.all.order(created_at: :desc)
    @image = ExtImage.new
  end

  def create
    folder_id = params['folder_id']
    folder = folder_id.blank? ? get_default_folder : Folder.find(folder_id)
    @image = folder.images.create(uploaded_image_params)
    if @image.valid?
      url = original_url(@image.image)
      respond_to do |f|
        f.json {render json: {result: 0, original_url: url}}
        f.html {redirect_to :action => :index}
      end
    else
      respond_to do |f|
        f.json {render status: :unprocessable_entity, json: {result: 1, errors: @image.errors.messages}}
        f.html {
          flash[:errors] = @image.errors.messages
          redirect_to :action => :index
        }
      end
    end
  end

  def destroy
    render status: 404 if @image.nil?
    @image.to_trash
    respond_to do |f|
      f.json {render json: {result: 0, original_url: @image.image.url}}
      f.html {redirect_to :action => :index}
    end

  end

  def destroy_and_unpublish_image
    render status: 404 if @image.nil?
    @image.destroy!
    respond_to do |f|
      f.json {render json: {result: 0}}
      f.html {redirect_to action: :index}
    end
  end

  def show
    render status: 404 if @image.nil?
    render json: {
      result: 0,
      original_url: original_url(@image.image),
      thumb: original_url(@image.image.thumb)
    }
  end

  private

  def uploaded_image_params
    params.require(:ext_image).permit(:image)
  end

  def set_image
    @image = ExtImage.find(params['id'])
  end


  def get_default_folder
    Folders.find_by(path: '/common')
  end

end

app/views/ext_images/_ext_image.html.erb
<div class="media image_preview_row" data-scope-id="<%= ext_image.id %>">
  <input type="hidden" name="scope-object" value="<%= ext_image.id %>">
  <div class="media-left">
    <a href="<%= ext_image.image.url %>">
      <img class="media-object" src="<%= ext_image.preview %>" style="width: 200px"/>
    </a>
  </div>
  <div class="media-body">
    <div class="codes">
      <%= original_url(ext_image.image) %>
      <br/>
      <%= original_url(ext_image.image.thumb) %>
      <br/>
      <textarea disabled>
        <a href=" <%= original_url(ext_image.image) %> ">
          <img src="<%= original_url(ext_image.image.thumb) %>" style="" class=""/>
        </a>
      </textarea>
    </div>
    <div style="text-align: left">
        <button class="btn btn-danger delete-button">Delete</button>
    </div>
  </div>
</div>

app/views/ext_images/_upload_panel.html.erb
<% folder_id = folder_id.present? ? folder_id : '' %>
<%= form_tag(ext_images_path, method: 'post', multipart: true) do %>
    <span class="btn btn-success fileinput-button">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Add files...</span>
      <!-- The file input field used as target for the file upload widget -->
      <%= file_field_tag 'ext_image[image]', multiple: true, id: 'fileupload' %>
      </span>
    <span class="btn btn-info clearlist-button">Clear list</span>
    <%= hidden_field_tag 'folder_id', folder_id, id: 'folder_id' %>
<% end %>
<br>

<!-- The global progress bar -->
<div id="progress" class="progress">
  <div class="progress-bar progress-bar-success"></div>
</div>
<!-- The container for the uploaded files -->
<div id="files" class="files"></div>

app/views/ext_images/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(@image, url: {action: 'create'}, html: {class: 'form'}) do |f| %>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.text_field :folder, class: 'form-control', placeholder: 'Folder' %>
        </div>
        <br/>
        <%= f.submit "Submit", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

<%= render @images %>

app/views/ext_images/upload_modal.html.erb
<% folder_id = @folder.present? ? @folder.id : nil %>
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

      </div>
      <div class="modal-body">
        <%= render partial: 'upload_panel', locals: {folder: folder_id} %>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>

  </div>

</div>