config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/folder')
  get "/sign_up", to: 'session#show'
  post "/sign_up", to: 'session#signup', as: 'signup'
  get 'logout', to: 'session#logout', as: 'logout'

  resources :ext_images do
  end
  resources :folders do
    get 'upload', on: :member
  end
  get '/folder', to: 'folders#show', as: 'folders_root'
  post '/ext_image/:id/destroy', to: 'ext_images#destroy', as: 'ext_image_delete'

  post '/uploads/common_images', to: 'common_uploads#common_image', as: 'common_images_upload'

  namespace :scanlet do
    resources :projects
    resources :groups do
      member do
        get 'translations'
      end
    end
    resources :translations, only: [:show, :new, :create]
    get '/groups/:group/add_scan', to: 'translations#new', as: 'add_scan_to_group'
  end
end

app/models/scanlet/group.rb
class Scanlet::Group < ApplicationRecord
  self.table_name =  'scanlet_groups'
  validates :name, presence: true
  belongs_to :project, :class_name => 'Scanlet::Project', foreign_key: "project_id"
  has_many :translations, :class_name => 'Translation', dependent: :destroy, foreign_key: "group_id"
end

app/models/scanlet/project.rb
class Scanlet::Project < ApplicationRecord
  self.table_name =  'scanlet_projects'
  validates :name, presence: true, uniqueness: true
  has_many :groups, :class_name => 'Group', dependent: :destroy, foreign_key: 'project_id'
  belongs_to :cover, :class_name => 'Common::ImageLink', optional: true

  TEST_IMAGE = Rails.root.join('test', 'fixtures', 'files', 'scan.png')

  def self.create_test_struct(project_name)

    ActiveRecord::Base.transaction do
      project = Scanlet::Project.create({name: project_name})
      project.save!
      p project
      group = Group.new({name: project_name + '_group1', project: project})
      group.save
      (1..3).each do |index|
        File.open(TEST_IMAGE) do |f|
          scan = Scanlet::Scan.create({image: f})
          group.translations.build({
                                             scan: scan,
                                             index: index
                                         })
          group.save
        end
      end
    end
  end

  def self.clear_all
    Scanlet::Project.destroy_all
  end
end

app/models/scanlet/scan.rb
class Scanlet::Scan < ApplicationRecord
  self.table_name =  'scanlet_scans'
  mount_uploader :image, ScanUploader
end

app/models/scanlet/translation.rb
class Scanlet::Translation < ApplicationRecord
  self.table_name = 'scanlet_translations'
  belongs_to :group, :class_name => 'Group', required: false, foreign_key: 'group_id'
  belongs_to :scan, :class_name => 'Scanlet::Scan', required: true, foreign_key: 'scan_id', dependent: :destroy
  accepts_nested_attributes_for :scan
end

app/controllers/scanlet/groups_controller.rb
class Scanlet::GroupsController < ApplicationController

  layout 'application'

  def show
    @presenter = Scanlet::GroupPresenter.new(:view, Scanlet::Group.find(params[:id]))
    render "scanlet/groups/show"
  end

  def edit
    @presenter = Scanlet::GroupPresenter.new(:edit, Scanlet::Group.find(params[:id]), params)
    if request.xhr?
      render @presenter.respond_json
    else
      render "scanlet/groups/edit"
    end
  end

  def new
    @presenter = Scanlet::GroupPresenter.new(:new, Scanlet::Group.new, params)
    render "scanlet/groups/edit"
  end

  def create
    group = Scanlet::Group.create!(group_params)
    if request.xhr?
      @presenter = Scanlet::GroupPresenter.new(:view, group)
      render @presenter.respond_json
    else
      if group.valid?
        redirect_to action: "show", id: group.id
      else
        @presenter = Scanlet::GroupPresenter.new(:new, group, params)
        render "scanlet/groups/edit"
      end
    end
  end

  def update
    group = Scanlet::Group.find(params[:id])
    group.update_attributes(group_params)
    if request.xhr?
      @presenter = Scanlet::GroupPresenter.new(:view, group)
      render @presenter.respond_json
    else
      if group.valid?
        redirect_to action: "show", id: group.id
      else
        @presenter = Scanlet::GroupPresenter.new(:edit, group, params)
        render "scanlet/groups/edit"
      end
    end
  end

  def translations
    @translations = Scanlet::Group.find(params[:id]).translations.order(:index => :asc)
    render :partial => "scanlet/groups/pages", locals: {translations: @translations}
  end

  def edit_translations

  end

  private

  def group_params
    params.require(:group).permit(:name, :index, :project_id)
  end

end

app/controllers/scanlet/projects_controller.rb
class Scanlet::ProjectsController < ApplicationController

  layout 'application'

  def index
    @projects = Scanlet::Project.all
  end

  def show
    @project = Scanlet::Project.find(params[:id])
    @editable = false
  end

  def new
    @project = Scanlet::Project.new
    @editable = true
    render 'show'
  end

  def edit
    @project = Scanlet::Project.find(params[:id])
    @editable = true
    render 'show'
  end

  def create
    @project = Scanlet::Project.new

    @project.name = params[:title]
    @project.description = params[:description]

    if params[:cover_id].present?
      cover_id = params[:cover_id]
      @project.create_cover({target_id: cover_id})
    end
    @project.save!

    if request.xhr?
      render json: {
          result: 0,
          object_id: @project.id,
          goto: scanlet_project_path(@project.id)
      }
    else
      redirect_to action: :show, id: @project.id
    end
  end

  def update

    @project = Scanlet::Project.find(params[:id])

    @project.name = params[:title]
    @project.description = params[:description]


    old_cover = nil
    if params[:cover_id].present?
      old_cover = @project.cover
      cover_id = params[:cover_id]
      @project.create_cover({target_id: cover_id})
    end
    @project.save!
    if old_cover.present?
      old_cover.destroy!
    end


    if request.xhr?
      render json: {
          result: 0
      }
    else
      render action: :show, id: @project.id
    end

  end

end

app/controllers/scanlet/translations_controller.rb
class Scanlet::TranslationsController < ApplicationController

  layout 'application'

  def show
    @translation = Scanlet::Translation.find(params[:id])
  end

  def new
    unless params[:group].blank?
      @group = Scanlet::Group.find(params[:group])
    end
    @translation = Scanlet::Translation.new(group: @group)
  end

  def create
    group_id = params[:group_id]
    image_ids = []
    unless params[:image_id].nil?
      image_ids << params[:image_id]
    end
    unless params[:image_ids].nil?
      image_ids = params[:image_ids]
    end

    last = Scanlet::Group.find(group_id).translations.order(:index => :asc).last
    if last.nil?
      last_index = 0
    else
      last_index = last.index
    end
    ops = []
    image_ids.each_with_index do |id, index|
      op = Scanlet::TranslationOperations::AddNewTranslation.new(group_id, id)
      op.index = last_index + index + 1
      op.call
      ops << op
    end

    if request.xhr?
      render json: {
          result: 0,
          object_id: ops.map {|op| op.result.id }
      }
    end
  end


  private

  def translation_params
    params.require(:scanlet_translation).permit(:translation, :group_id)
  end

end

app/views/scanlet/projects/index.html.erb
<div data-scope="scanlet-projects">
  <div class="row">
    <div class="col-xs-12 toolbar">
      <%= link_to "projects/new", class: "btn btn-success" do %>
          <i class="fa fa-plus"></i>
          <span>New project</span>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 listing-container">
      <% @projects.each do |project| %>
          <div class="media project-item">
            <div class="media-left">
              <%= link_to scanlet_project_path(project.id) do %>
                  <img src="<%= project.cover.present? ? project.cover.target.file.url : dummy_url %>" class="media-object" alt="">
              <% end %>
            </div>
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to scanlet_project_path(project.id) do %>
                    <%= project.name %>
                <% end %>
              </h4>
              <p class="description">
                <%= project.description.blank? ? "No description" : project.description %>
              </p>
            </div>
          </div>
      <% end %>
    </div>
  </div>

</div>

app/views/scanlet/projects/new.html.erb
<div data-scope="scanlet-projects-new">

</div>

app/views/scanlet/projects/show.html.erb
<div data-scope="scanlet-groups">
  <%= link_to scanlet_projects_path, class: 'navigation-back' do %>
    Back to projects
  <% end %>
  <form id="project-description-form" method="post" action="<%= @project.id.nil? ? scanlet_projects_path : scanlet_project_path(@project.id) %>" data-ajax="true">
    <input type="hidden" name="_method" value="<%= @project.id.nil? ? 'post' : 'patch' %>">
    <div class="controls">
      <input type="submit" class="btn btn-success" value="Submit"/>
    </div>
    <div id="project-description">
      <div class="cover"
           data-upload-path="<%= common_images_upload_path %>"
           data-form-param-name="cover_id"
           data-upload-param-name="file"
           data-editable="image"
      >
        <% if @project.cover.present? %>
          <%= image_tag @project.cover.target.file.url, class: "img-responsive current" %>
        <% else %>
          <img src="<%= dummy_url %>" alt="" class="img-responsive current">
        <% end %>
      </div>
      <div class="details">
        <h3 class="title" data-editable="true">
          <span id="title"><%= @project.name %></span>
          <input type="text" name="title" data-editor data-display="#title">
        </h3>
        <p class="description" data-editable="true">
          <span id="description" class="content"><%= @project.description || "No description" %></span>
          <textarea name="description" cols="30" rows="10"
                    data-display="#description"
          ></textarea>
        </p>
      </div>
    </div>
  </form>
  <% unless @project.id.nil? %>
    <div class="row">
      <div class="col-xs-12 buttons">
        <a href="<%= new_scanlet_group_path(project_id: @project.id) %>" class="btn btn-success">
          <i class="fa fa-plus"></i>
          <span>New</span>
        </a>
      </div>
      <div class="col-xs-12 listing-container">
        <% @project.groups.order(:index => :desc).each do |group| %>
          <%= link_to scanlet_group_path(group), class: 'item-wrapper' do %>
            <div class="item">
              <h4><%= group.name %></h4>
              <span class="updated_at"><%= group.updated_at %></span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>